import { generateCandidates } from './candidate-generator';
import { validateLevelConstraints } from './constraints';
import { deriveDifficultyMetrics, scoreDifficulty } from './difficulty';
import { solveLevel } from './solver';
import type { LevelArtifact, LevelRecipe } from './types';

export type GenerationResult =
  | { readonly kind: 'accepted'; readonly artifact: LevelArtifact; readonly candidatesAttempted: number }
  | {
      readonly kind: 'rejected';
      readonly recipeId: string;
      readonly candidatesAttempted: number;
      readonly closestScore: number | null;
      readonly reasons: readonly string[];
    };

export function generateLevelArtifact(recipe: LevelRecipe, ordinal: number): GenerationResult {
  let candidatesAttempted = 0;
  let closestScore: number | null = null;
  let closestDistance = Number.POSITIVE_INFINITY;
  const reasons = new Set<string>();

  for (const candidate of generateCandidates(recipe)) {
    candidatesAttempted += 1;
    const solution = solveLevel(candidate, {
      quantumMs: 50,
      minimumInputSpacingMs: 300,
      maxVisitedStates: recipe.generationBudget.maxVisitedStates,
      maxElapsedMs: recipe.generationBudget.maxElapsedMs,
      requiredPeakBufferOccupancy: recipe.requiresFullBuffer ? 5 : undefined,
    });
    if (solution.kind !== 'solved') {
      reasons.add(solution.kind === 'exhausted' ? 'unsolvable' : 'solver-budget-exceeded');
      continue;
    }

    const constraints = validateLevelConstraints(candidate, recipe, solution.witness);
    if (!constraints.ok) {
      reasons.add(constraints.reason);
      continue;
    }

    const metrics = deriveDifficultyMetrics(candidate, solution.metrics);
    const difficulty = scoreDifficulty(metrics);
    const distance = Math.abs(difficulty.score - recipe.targetDifficulty);
    if (distance < closestDistance) {
      closestDistance = distance;
      closestScore = difficulty.score;
    }
    if (distance > recipe.difficultyTolerance) {
      reasons.add('difficulty-outside-target');
      continue;
    }

    return {
      kind: 'accepted',
      candidatesAttempted,
      artifact: {
        id: candidate.id,
        level: candidate,
        title: recipe.title,
        ordinal,
        difficulty: difficulty.score,
        difficultyVersion: difficulty.version,
        metrics,
        recipeId: recipe.id,
        seed: recipe.seed,
        requiresFullBuffer: recipe.requiresFullBuffer ?? false,
        witness: solution.witness,
      },
    };
  }

  return {
    kind: 'rejected',
    recipeId: recipe.id,
    candidatesAttempted,
    closestScore,
    reasons: [...reasons],
  };
}

export function generateCatalog(recipes: readonly LevelRecipe[]): readonly LevelArtifact[] {
  return recipes.map((recipe, index) => {
    const result = generateLevelArtifact(recipe, index + 1);
    if (result.kind === 'rejected') {
      throw new Error(
        `Failed to generate ${result.recipeId}: ${result.reasons.join(', ')}; ` +
        `closest score ${String(result.closestScore)} after ${result.candidatesAttempted} candidate(s)`,
      );
    }
    return result.artifact;
  });
}

function sortObjectKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortObjectKeys);
  if (value === null || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.entries(value)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, nested]) => [key, sortObjectKeys(nested)]),
  );
}

export function serializeCatalog(artifacts: readonly LevelArtifact[]): string {
  const serialized = JSON.stringify(sortObjectKeys(artifacts), null, 2);
  return [
    "import type { LevelArtifact } from '../../level-tools/types';",
    '',
    '// Generated by npm run levels:generate. Do not edit.',
    `export const GENERATED_LEVEL_CATALOG = ${serialized} as const satisfies readonly LevelArtifact[];`,
    '',
  ].join('\n');
}
