import { describe, expect, it } from 'vitest';
import { generateLevelArtifact, serializeCatalog } from './pipeline';
import type { LevelRecipe } from './types';

const RECIPE: LevelRecipe = {
  id: 'pipeline-one-pixel',
  title: 'Pipeline one pixel',
  board: {
    kind: 'ascii',
    rows: ['B'],
    symbols: { B: 'blue' },
  },
  seed: 12,
  targetDifficulty: 8,
  difficultyTolerance: 0,
  generationBudget: {
    maxCandidates: 2,
    maxVisitedStates: 100,
    maxElapsedMs: 1_000,
  },
  speedTrackUnitsPerSecond: 60,
};

describe('generateLevelArtifact', () => {
  it('accepts the first deterministic candidate inside target tolerance', () => {
    const result = generateLevelArtifact(RECIPE, 3);

    expect(result.kind).toBe('accepted');
    if (result.kind !== 'accepted') return;
    expect(result.artifact).toMatchObject({
      id: RECIPE.id,
      title: RECIPE.title,
      ordinal: 3,
      difficulty: 8,
      recipeId: RECIPE.id,
      seed: RECIPE.seed,
      requiresFullBuffer: false,
    });
    expect(result.artifact.witness).toEqual([
      { atMs: 0, source: { kind: 'stack', index: 1 } },
    ]);
  });

  it('returns byte-stable accepted data for the same recipe', () => {
    expect(JSON.stringify(generateLevelArtifact(RECIPE, 1)))
      .toBe(JSON.stringify(generateLevelArtifact(RECIPE, 1)));
  });

  it('reports the closest score after candidate budget exhaustion', () => {
    const result = generateLevelArtifact({
      ...RECIPE,
      targetDifficulty: 100,
    }, 1);

    expect(result).toMatchObject({
      kind: 'rejected',
      recipeId: RECIPE.id,
      candidatesAttempted: 2,
      closestScore: 8,
      reasons: ['difficulty-outside-target'],
    });
  });
});

describe('serializeCatalog', () => {
  it('emits timestamp-free TypeScript with stable property ordering', () => {
    const result = generateLevelArtifact(RECIPE, 1);
    if (result.kind !== 'accepted') throw new Error('fixture must be accepted');

    const serialized = serializeCatalog([result.artifact]);

    expect(serialized).toContain('// Generated by npm run levels:generate. Do not edit.');
    expect(serialized).toContain('export const GENERATED_LEVEL_CATALOG =');
    expect(serialized).toContain('satisfies readonly LevelArtifact[];');
    expect(serialized).not.toMatch(/generatedAt|timestamp/);
    expect(serializeCatalog([result.artifact])).toBe(serialized);
  });
});
